sudo: required
services:
  -docker

before_install:
  - docker build -t Utkal20/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true Utkal20/docker_react npm run test

language: generic 